name = "desafio-02"
bin = "bin/desafio-02"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = false
with_docker = true
with_grifts = true
as_web = true
as_api = false
