version: '3'

services:

  redis:
    image: redis:alpine
    container_name: commerce-redis
    volumes:
      - ./redisdata:/data
    ports:
      - 6379:6379
    networks:
      - code-commerce

networks:
  code-commerce:
    driver: bridge